### ISSUE TITLE
FeatureRequest : helm compose up --release releaseName

### ISSUE THREAD

**Issue by alexfokuk** [seacrew/helm-compose#110]
In docker-compose, we can docker-compose up -d ${serviceName}

However, seems not available in helm compose

**Comment by tuunit** [comment]
Hi @alexfokuk,

this was actually an intended change in comparison to `docker-compose`, to truly keep everything in code. I might reconsider it but in that case a decision has to be made first. On how the revisions will reflect it. Either by introducing an `enabled` flag or removing the releases from the revision file.

**Comment by tuunit** [comment]
Hi @alexfokuk,

what would be your desired behaviour for `helm compose down release-x`? A full helm uninstall of the release?

**Comment by alexfokuk** [comment]
i think the behaviour is same,   `helm compose down release-x` to uninstall release-x only.

Let me explain more why this features is useful. 

e.g. : If we have wordpress and wordpress2

```
  wordpress:
    chart: bitnami/wordpress
    chartVersion: 14.3.2
  wordpress2:
    chart: bitnami/wordpress
    chartVersion: 15.2.22
```

If update wordpress2, it will also updating revision of wordpress as well.
