### ISSUE TITLE
Simple test doesn't work

### ISSUE THREAD

**Issue by dberuben** [seacrew/helm-compose#16]
Hi,

I'm doing this simple override but nothing happen, Am I wrong somewhere?

```
apiVersion: 1.0

storage:
  name: mycompose
  type: local # default
  path: .hcstate # default

releases:
  wordpress:
    chart: bitnami/wordpress
    chartVersion: 14.3.2
    values:
      resources:
        limits:
          memory: 1G
          cpu: 1G
        requests:
          memory: 512Mi
          cpu: 300m
      replicaCount: 2
  wordpress2:
    chart: bitnami/wordpress
    chartVersion: 15.2.22
    namespace: default
    values:
      replicaCount: 3
  postgres:
    chart: bitnami/postgresql
    chartVersion: 12.1.9
    namespace: default

repositories:
  bitnami: https://charts.bitnami.com/bitnami
  ```
  
  the output is 
  
  ```
  (☸|lspay-trial-eu-west-1:default)➜  helm-compose helm compose up
wordpress |		unknown flag: --set-json
wordpress2 |		unknown flag: --set-json
postgres |		Release "postgres" has been upgraded. Happy Helming!
postgres |		NAME: postgres
postgres |		LAST DEPLOYED: Thu Aug 31 10:53:05 2023
postgres |		NAMESPACE: default
postgres |		STATUS: deployed
postgres |		REVISION: 5
postgres |		TEST SUITE: None
postgres |		NOTES:
postgres |		CHART NAME: postgresql
postgres |		CHART VERSION: 12.1.9
postgres |		APP VERSION: 15.1.0
...
  ```

**Comment by dberuben** [comment]
same with ValuesFile:

```
apiVersion: 1.0

storage:
  name: mycompose
  type: local # default
  path: .hcstate # default

releases:
  wordpress:
    chart: bitnami/wordpress
    chartVersion: 14.3.2
    namespace: default
    valueFiles:
      - ./test.yaml
#  postgres:
#    chart: bitnami/postgresql
#    chartVersion: 12.1.9
#    namespace: default

repositories:
  bitnami: https://charts.bitnami.com/bitnami
```

```
(☸|lspay-trial-eu-west-1:default)➜  helm-compose cat test.yaml
replicatCount: 2
```

Nothing happen
