### ISSUE TITLE
feat: only upgrade helm on change

### ISSUE THREAD

**Issue by dberuben** [seacrew/helm-compose#22]
Did I miss something?

```
(☸|lspay-trial-eu-west-1:default)➜  helm-compose-test helm ls
NAME       	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART            	APP VERSION
helloworld1	default  	4       	2023-09-01 15:56:18.159761 +0200 CEST	deployed	hello-world-0.6.0
helloworld2	default  	4       	2023-09-01 15:56:18.115698 +0200 CEST	deployed	hello-world-0.6.0
(☸|lspay-trial-eu-west-1:default)➜  helm-compose-test helm plugin list
NAME   	VERSION	DESCRIPTION
compose	1.2.0
```

```
apiVersion: 1.1

storage:
  name: mycompose
  type: local # default
  path: .hcstate # default

releases:
  helloworld1:
    chart: sikalabs/hello-world 
    values:
      replicas: 2
  helloworld2:
    chart: sikalabs/hello-world 
    values:
      replicas: 2
repositories:
  sikalabs: https://helm.sikalabs.io

```
